version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis:6379
    volumes:
      - .:/app
    command: ["sleep", "1d"]
